spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unit_test_db?useSSL=false
    driver-class-name: org.h2.Driver
    username: root
    password: Online12
  jpa:
    hibernate:
      ddl-auto: create-drop
        